/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MediaRouteImport } from './routes/media'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminSetupRouteImport } from './routes/admin-setup'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthMfaSetupRouteImport } from './routes/auth.mfa-setup'
import { Route as AuthMfaRouteImport } from './routes/auth.mfa'
import { Route as AuthenticatedWarRoomRouteImport } from './routes/_authenticated/war-room'
import { Route as AuthenticatedAdminYouthRegistrationsRouteImport } from './routes/_authenticated/admin.youth-registrations'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as ApiPublicBootstrapSuperAdminRouteImport } from './routes/api/public/bootstrap.super-admin'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMfaSetupRoute = AuthMfaSetupRouteImport.update({
  id: '/mfa-setup',
  path: '/mfa-setup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedWarRoomRoute = AuthenticatedWarRoomRouteImport.update({
  id: '/war-room',
  path: '/war-room',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminYouthRegistrationsRoute =
  AuthenticatedAdminYouthRegistrationsRouteImport.update({
    id: '/admin/youth-registrations',
    path: '/admin/youth-registrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicBootstrapSuperAdminRoute =
  ApiPublicBootstrapSuperAdminRouteImport.update({
    id: '/api/public/bootstrap/super-admin',
    path: '/api/public/bootstrap/super-admin',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-setup': typeof AdminSetupRoute
  '/auth': typeof AuthRouteWithChildren
  '/donate': typeof DonateRoute
  '/manifesto': typeof ManifestoRoute
  '/media': typeof MediaRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/war-room': typeof AuthenticatedWarRoomRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/mfa-setup': typeof AuthMfaSetupRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/youth-registrations': typeof AuthenticatedAdminYouthRegistrationsRoute
  '/api/public/bootstrap/super-admin': typeof ApiPublicBootstrapSuperAdminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-setup': typeof AdminSetupRoute
  '/auth': typeof AuthRouteWithChildren
  '/donate': typeof DonateRoute
  '/manifesto': typeof ManifestoRoute
  '/media': typeof MediaRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/war-room': typeof AuthenticatedWarRoomRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/mfa-setup': typeof AuthMfaSetupRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/youth-registrations': typeof AuthenticatedAdminYouthRegistrationsRoute
  '/api/public/bootstrap/super-admin': typeof ApiPublicBootstrapSuperAdminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/admin-setup': typeof AdminSetupRoute
  '/auth': typeof AuthRouteWithChildren
  '/donate': typeof DonateRoute
  '/manifesto': typeof ManifestoRoute
  '/media': typeof MediaRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/volunteer': typeof VolunteerRoute
  '/_authenticated/war-room': typeof AuthenticatedWarRoomRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/mfa-setup': typeof AuthMfaSetupRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/youth-registrations': typeof AuthenticatedAdminYouthRegistrationsRoute
  '/api/public/bootstrap/super-admin': typeof ApiPublicBootstrapSuperAdminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin-setup'
    | '/auth'
    | '/donate'
    | '/manifesto'
    | '/media'
    | '/register'
    | '/sitemap.xml'
    | '/volunteer'
    | '/war-room'
    | '/auth/mfa'
    | '/auth/mfa-setup'
    | '/admin/users'
    | '/admin/youth-registrations'
    | '/api/public/bootstrap/super-admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-setup'
    | '/auth'
    | '/donate'
    | '/manifesto'
    | '/media'
    | '/register'
    | '/sitemap.xml'
    | '/volunteer'
    | '/war-room'
    | '/auth/mfa'
    | '/auth/mfa-setup'
    | '/admin/users'
    | '/admin/youth-registrations'
    | '/api/public/bootstrap/super-admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin-setup'
    | '/auth'
    | '/donate'
    | '/manifesto'
    | '/media'
    | '/register'
    | '/sitemap.xml'
    | '/volunteer'
    | '/_authenticated/war-room'
    | '/auth/mfa'
    | '/auth/mfa-setup'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/youth-registrations'
    | '/api/public/bootstrap/super-admin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AuthRoute: typeof AuthRouteWithChildren
  DonateRoute: typeof DonateRoute
  ManifestoRoute: typeof ManifestoRoute
  MediaRoute: typeof MediaRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VolunteerRoute: typeof VolunteerRoute
  ApiPublicBootstrapSuperAdminRoute: typeof ApiPublicBootstrapSuperAdminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-setup': {
      id: '/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mfa-setup': {
      id: '/auth/mfa-setup'
      path: '/mfa-setup'
      fullPath: '/auth/mfa-setup'
      preLoaderRoute: typeof AuthMfaSetupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/mfa': {
      id: '/auth/mfa'
      path: '/mfa'
      fullPath: '/auth/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/war-room': {
      id: '/_authenticated/war-room'
      path: '/war-room'
      fullPath: '/war-room'
      preLoaderRoute: typeof AuthenticatedWarRoomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/youth-registrations': {
      id: '/_authenticated/admin/youth-registrations'
      path: '/admin/youth-registrations'
      fullPath: '/admin/youth-registrations'
      preLoaderRoute: typeof AuthenticatedAdminYouthRegistrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/bootstrap/super-admin': {
      id: '/api/public/bootstrap/super-admin'
      path: '/api/public/bootstrap/super-admin'
      fullPath: '/api/public/bootstrap/super-admin'
      preLoaderRoute: typeof ApiPublicBootstrapSuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedWarRoomRoute: typeof AuthenticatedWarRoomRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminYouthRegistrationsRoute: typeof AuthenticatedAdminYouthRegistrationsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedWarRoomRoute: AuthenticatedWarRoomRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminYouthRegistrationsRoute:
    AuthenticatedAdminYouthRegistrationsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthMfaRoute: typeof AuthMfaRoute
  AuthMfaSetupRoute: typeof AuthMfaSetupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthMfaRoute: AuthMfaRoute,
  AuthMfaSetupRoute: AuthMfaSetupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminSetupRoute: AdminSetupRoute,
  AuthRoute: AuthRouteWithChildren,
  DonateRoute: DonateRoute,
  ManifestoRoute: ManifestoRoute,
  MediaRoute: MediaRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VolunteerRoute: VolunteerRoute,
  ApiPublicBootstrapSuperAdminRoute: ApiPublicBootstrapSuperAdminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
